# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: "Deployment pipeline for $(Build.DefinitionName)"
trigger:
- master
variables:
- group: PipelineVars

stages:
- stage: Deploy
  jobs:
  #Deployment to Dev
  - job: Development
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Cache@2
      displayName: Cache Maven build from local repo
      inputs:
        key: maven | "$(Agent.OS)" | "$(Pipeline.Workspace)/s/$(Build.Repository.Name)/pom.xml"
        path: $(MAVEN_CACHE_FOLDER)
        cacheHitVar: CacheRestored
        restoreKeys: >
          maven | "$(Agent.OS)"
          maven
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
