# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: "Deployment pipeline for $(Build.DefinitionName)"
trigger:
- master
variables:
- group: PipelineVars

stages:
- stage: Deploy
  jobs:
  #Deployment to Dev
  - job: Development
    variables:
    - group: Anypoint Platform Vars
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DownloadSecureFile@1
      name: settingsxml
      inputs:
        secureFile: 'settings.xml'
    - task: DownloadSecureFile@1
      name: credentialsFile
      inputs:
        secureFile: 'credentials.json'
    - task: PowerShell@2
      displayName: Install Anypoint CLI and copy credentials
      inputs:
        targetType: inline
        script: |
          sudo npm install -g anypoint-cli@3.6.0
          mkdir ~/.anypoint
          cp $(credentialsFile.secureFilePath) ~/.anypoint/
          mkdir ~/.m2
          cp $(settingsxml.secureFilePath) ~/.m2/

    - task: Cache@2
      displayName: Cache Maven build from local repo
      inputs:
        key: maven | "$(Agent.OS)" | "$(Pipeline.Workspace)/s/$(Build.Repository.Name)/pom.xml"
        path: $(MAVEN_CACHE_FOLDER)
        cacheHitVar: CacheRestored
        restoreKeys: >
          maven | "$(Agent.OS)"
          maven
    - task: Maven@3
      displayName: Package Application
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: PowerShell@2
      displayName: Deploy Application using CLI 
      inputs:
        targetType: inline
        script: |
          anypoint-cli runtime-mgr cloudhub-application deploy --runtime "$(runtime)" --environment "$(environment)" --workers "$(workers)" --workerSize "$(workerSize)" --applicationName "$(applicationName)" 

    
